---

# IntelliJ supports Ctrl+clicking anchors to find usages and declarations... so, hyperlinks! Yooooooooo!
# Basically a table of contents; Ctrl+click on a heading in UPPER_SNAKE_CASE to jump back and forth between the
# table of contents and actual location in the map.
NAVIGATION:
  # The anchors that replace map key values must have the values of the keys that they replace.
  - &PDP pdp
  # This works magically because the anchor refers to the key of the mapping only, which is the string "subsystems".
  - &SUBSYSTEMS subsystems:
      # Other anchors, like these, become null list items and are explicitly ignored using @JsonInclude
      - &DRIVE_SUBSYSTEM
      - &CLIMBER_SUBSYSTEM
  - &COMMANDS commands:
      - &BUTTONS buttons:
          - &CLIMBER_COMMANDS
      - &DEFAULT_COMMANDS defaultCommands:
          - &DRIVE_DEFAULT_COMMAND
  - &UPDATER updater

# Anchors for transclusion into the rest of the map.
# Ignored by Jackson (so is NAVIGATION); can contain any valid YAML suitable for organizational purposes.
# Make sure there aren't any colons after the anchors; Jackson gives "Null key for a Map not allowed in JSON"
CONSTANTS:
  - MotorPorts:
      # Spinnyboiz
      - &leftMasterPort 1
      - &leftMasterSlave1Port 3
      - &leftMasterSlave2Port 5
      - &rightMasterPort 2
      - &rightMasterSlave1Port 4
      - &rightMasterSlave2Port 6
      - &climberMotorPort 13
  - DIOPorts:
      - &leftMasterEncoder1Port 2
      - &leftMasterEncoder2Port 3
      - &rightMasterEncoder1Port 0
      - &rightMasterEncoder2Port 1
  - JoystickPorts:
      - &driveJoystickPort 1
      - &mechanismsJoystickPort 0
  - SolenoidPorts:
      - &climberSolenoidForward 4
      - &climberSolenoidReverse 5
  - ButtonNumbers:
      - &climberWinchButtonNumber_reversed 7
      - &climberLowerButtonNumber 5
      - &climberRaiseButtonNumber 6
      - &climberWinchButtonNumber 8
  - Other:
      - &winchSpeed 1.0
      - &winchSpeed_reversed -1.0


# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false

########################################################################################################################
*PDP:
  frc.team449.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75


########################################################################################################################
*SUBSYSTEMS:
  #***********************************************************************************************************************
  - *DRIVE_SUBSYSTEM
  - frc.team449.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
      '@id': drive
      #Wheelbase: 2.14
      leftMaster:
        frc.team449.generalInterfaces.SmartMotor:
          &Left_Master
          '@id': leftMaster
          type: SPARK
          name: left
          port: *leftMasterPort
          PDP:
            frc.team449.jacksonWrappers.PDP: PDP
          reverseOutput: true
          enableBrakeMode: true
#          postEncoderGearing: 0.13333333333
          unitPerRotation: 0.47877872 #meters per rotation
          currentLimit: 50
          enableVoltageComp: true
          encoderCPR: 256
          startingGear: LOW
          perGearSettings:
            - &Low_Gear
              gear: LOW
              postEncoderGearing: 0.0488998
              maxSpeed: 2.3
              kP: 0
              feedForwardCalculator:
                frc.team449.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.128
                  kV: 5.23
                  kA: 0.0698
            - &High_Gear
              gear: HIGH
              postEncoderGearing: 0.12936611
              maxSpeed: 5.2
              kP: 0
              feedForwardCalculator:
                frc.team449.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.156
                  kV: 2.01
                  kA: 0.154
          slaveSparks:
            - port: *leftMasterSlave1Port
              inverted: false
            - port: *leftMasterSlave2Port
              inverted: false
      rightMaster:
        frc.team449.generalInterfaces.SmartMotor:
          <<: *Left_Master
          '@id': rightMaster
          type: SPARK
          name: right
          port: *rightMasterPort
          reverseOutput: false
          perGearSettings:
            - <<: *Low_Gear
              feedForwardCalculator:
                frc.team449.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.139
                  kV: 5.17
                  kA: 0.0554
            - <<: *High_Gear
              feedForwardCalculator:
                frc.team449.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.165
                  kV: 2.01
                  kA: 0.155
          slaveSparks:
            - port: *rightMasterSlave1Port
              PDP: PDP
              inverted: false
            - port: *rightMasterSlave2Port
              PDP: PDP
              inverted: false
      startingOverrideAutoshift: false
      ahrs:
        frc.team449.jacksonWrappers.MappedAHRS:
          '@id': navX
          port: kMXP
          invertYaw: true
      trackWidthMeters: 0.61755
      shiftComponent:
        frc.team449.components.ShiftComponent:
          '@id': driveShiftComponent
          otherShiftables:
            - frc.team449.jacksonWrappers.MappedSparkMaxExternalEncoder:
                leftMaster
            - frc.team449.jacksonWrappers.MappedSparkMaxExternalEncoder:
                rightMaster
          piston:
            '@id': driveShifter
            module: 0
            forward: 0
            reverse: 1
          startingGear: LOW

  - *CLIMBER_SUBSYSTEM
  - frc.team449._2020.climber.UnsafeWinchingClimber:
      '@id': climber
      motorSubsystem:
        frc.team449._2020.multiSubsystem.AnalogMotorSingleSpeed:
          '@id': climberMotorSubsystem
          speed: *winchSpeed
          motor:
            frc.team449.generalInterfaces.SmartMotor:
              '@id': climberMotor
              name: climberMotor
              type: SPARK
              port: *climberMotorPort
              enableBrakeMode: false
      solenoidSubsystem:
        frc.team449._2020.multiSubsystem.SolenoidSimple:
          '@id': climberSolenoidSystem
          piston:
            '@id': climberSolenoid
            module: 0
            forward: *climberSolenoidForward
            reverse: *climberSolenoidReverse


*COMMANDS:
  ########################################################################################################################
  *BUTTONS:
    - *CLIMBER_COMMANDS
    - button:
        frc.team449.oi.buttons.SimpleButton:
          '@id': climberRaiseButton
          joystick:
            frc.team449.jacksonWrappers.MappedJoystick:
              '@id': mechanismsJoystick
              port: *mechanismsJoystickPort
          buttonNumber: *climberRaiseButtonNumber
      command:
        frc.team449._2020.climber.commands.SetClimberWithArmState:
          '@id': climberRaiseCommand
          subsystem:
            frc.team449._2020.climber.UnsafeWinchingClimber:
              climber
          state: "RAISE"
      action: WHEN_PRESSED
    - button:
        frc.team449.oi.buttons.SimpleButton:
          '@id': climberLowerButton
          joystick:
            frc.team449.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: *climberLowerButtonNumber
      command:
        frc.team449._2020.climber.commands.SetClimberWithArmState:
          '@id': climberLowerCommand
          subsystem:
            frc.team449._2020.climber.UnsafeWinchingClimber:
              climber
          state: "LOWER"
      action: WHEN_PRESSED
    - button:
        frc.team449.oi.buttons.SimpleButton:
          '@id': climberWinchButton_press
          joystick:
            frc.team449.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: *climberWinchButtonNumber
      command:
        frc.team449._2020.multiSubsystem.commands.TurnMotorOn:
          '@id': climberWinchCommand_press
          subsystem:
            frc.team449._2020.climber.UnsafeWinchingClimber:
              climber
      action: WHEN_PRESSED
    - button:
        frc.team449.oi.buttons.SimpleButton:
          '@id': climberWinchButton_release
          joystick:
            frc.team449.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: *climberWinchButtonNumber
      command:
        frc.team449._2020.multiSubsystem.commands.TurnMotorOff:
          '@id': climberWinchCommand_release
          subsystem:
            frc.team449._2020.climber.UnsafeWinchingClimber:
              climber
      action: WHEN_RELEASED

    ## TEST COMMANDS
    - button:
        frc.team449.oi.buttons.SimpleButton:
          '@id': climberWinchButton_reversed_press
          joystick:
            frc.team449.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: *climberWinchButtonNumber_reversed
      command:
        frc.team449._2020.multiSubsystem.commands.TurnMotorOn:
          '@id': climberWinchCommand_reversed_press
          subsystem:
            frc.team449._2020.multiSubsystem.AnalogMotorSingleSpeed:
              '@id': climberMotorReversed
              speed: *winchSpeed_reversed
              motor:
                frc.team449.generalInterfaces.SmartMotor:
                  climberMotor
      action: WHEN_PRESSED
    - button:
        frc.team449.oi.buttons.SimpleButton:
          '@id': climberWinchButton_reversed_release
          joystick:
            frc.team449.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: *climberWinchButtonNumber_reversed
      command:
        frc.team449._2020.multiSubsystem.commands.TurnMotorOff:
          '@id': climberWinchCommand_reversed_release
          subsystem:
            frc.team449._2020.multiSubsystem.AnalogMotorSingleSpeed:
              climberMotorReversed
      action: WHEN_RELEASED

  ########################################################################################################################
  *DEFAULT_COMMANDS:
    #***********************************************************************************************************************
    - *DRIVE_DEFAULT_COMMAND
    - subsystem:
        frc.team449.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
          drive
      command:
        frc.team449.drive.unidirectional.commands.UnidirectionalNavXShiftingDefaultDrive:
          '@id': defaultDriveCommand
          kP: 0.0
          kI: 0.0
          kD: 0.0
          maximumOutput: 1
          absoluteTolerance: 0
          deadband: 2
          maxAngularVelToEnterLoop: 3
          inverted: false
          highGearAngularCoefficient: 3
          rampComponent:
            frc.team449.generalInterfaces.doubleUnaryOperator.RampComponent:
              maxIncreasePerSecond: 2
              maxDecreasePerSecond: 1
          driveStraightLoopEntryTimer:
            '@id': driveStraightLoopEntryTimer
            bufferTimeSeconds: 0.15
          subsystem:
            frc.team449.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
              drive
          oi:
            frc.team449.oi.unidirectional.arcade.OIArcadeWithDPad:
              '@id': oi
              gamepad:
                frc.team449.jacksonWrappers.MappedJoystick:
                  '@id': driveJoystick
                  port: *driveJoystickPort
              rotThrottle:
                frc.team449.oi.throttles.ThrottlePolynomial:
                  &rotThrottle
                  '@id': rotThrottle
                  stick: driveJoystick
                  axis: 0
                  smoothingTimeSecs: 0.04
                  deadband: 0.08
                  inverted: false
                  polynomial:
                    frc.team449.generalInterfaces.doubleUnaryOperator.Polynomial:
                      '@id': rotPoly
                      powerToCoefficientMap: !!map
                        1: .5
                        3: .5
                  scale: .7
              fwdThrottle:
                frc.team449.oi.throttles.ThrottleSum:
                  '@id': fwdThrottle
                  throttles:
                    - frc.team449.oi.throttles.ThrottlePolynomial:
                        <<: *rotThrottle
                        '@id': posThrottle
                        axis: 3
                        inverted: false
                        deadband: 0.05
                        polynomial:
                          frc.team449.generalInterfaces.doubleUnaryOperator.Polynomial:
                            '@id': posPoly
                            powerToCoefficientMap: !!map
                              1: 2
                              3: 1
                    - frc.team449.oi.throttles.ThrottlePolynomial:
                        <<: *rotThrottle
                        '@id': negThrottle
                        axis: 2
                        inverted: true
                        deadband: 0.05
                        polynomial:
                          frc.team449.generalInterfaces.doubleUnaryOperator.Polynomial:
                            '@id': negPoly
                            powerToCoefficientMap: !!map
                              1: 2
                              3: 1
              invertDPad: false
              dPadShift: 0.1
              turnInPlaceRotScale: 1
              rescaleOutputs: true
              scaleRotByFwdPoly:
                frc.team449.generalInterfaces.doubleUnaryOperator.Polynomial:
                  '@id': scaleRotByFwdPoly
                  powerToCoefficientMap: !!map
                    0.5: 0.4
                    0: 0.2
                    #1 : 0.25
                    #2: 0.25
          autoshiftComponent:
            '@id': autoshiftComponent
            upshiftSpeed: 1.6
            downshiftSpeed: 1
            upshiftDebouncer:
              '@id': upshiftDebouncer
              bufferTimeSeconds: 0.06
            upshiftFwdThresh: 0.4

########################################################################################################################
*UPDATER:
  frc.team449.other.Updater:
    '@id': updater
    updatables:
      - frc.team449.jacksonWrappers.PDP: PDP
      - frc.team449.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
      - frc.team449.oi.unidirectional.arcade.OIArcadeWithDPad: oi
      - frc.team449.jacksonWrappers.MappedAHRS: navX
      - frc.team449._2020.climber.UnsafeWinchingClimber: climber
