---

# IntelliJ supports Ctrl+clicking anchors to find usages and declarations... so, hyperlinks! Yooooooooo!
# Basically a table of contents; Ctrl+click on a heading in UPPER_SNAKE_CASE to jump back and forth between the
# table of contents and actual location in the map.
NAVIGATION:
  # The anchors that replace map key values must have the values of the keys that they replace.
  - &PDP pdp
  # This works magically because the anchor refers to the key of the mapping only, which is the string "subsystems".
  - &SUBSYSTEMS subsystems:
      # Other anchors, like these, become null list items and are explicitly ignored using @JsonInclude
      - &DRIVE_SUBSYSTEM
      - &INTAKE_SUBSYSTEM
      - &FEEDER_SUBSYSTEM
      - &SHOOTER_SUBSYSTEM
  - &COMMANDS commands:
      - &BUTTONS buttons:
          - &DRIVE_COMMANDS
          - &INTAKE_COMMANDS
          - &FEEDER_COMMANDS
          - &SHOOTER_COMMANDS
      - &DEFAULT_COMMANDS defaultCommands:
          - &DRIVE_DEFAULT_COMMAND
          - &FEEDER_DEFAULT_COMMAND
      - &AUTONOMOUS_COMMANDS autoStartupCommand:
          - &SLALOM_PATH
  - &UPDATER updater

# Anchors for transclusion into the rest of the map.
# Ignored by Jackson (so is NAVIGATION); can contain any valid YAML suitable for organizational purposes.
# Make sure there aren't any colons after the anchors; Jackson gives "Null key for a Map not allowed in JSON"
CONSTANTS:
  - MotorPorts:
      - &leftMasterPort 1
      - &leftMasterSlave1Port 3
      - &leftMasterSlave2Port 5
      - &rightMasterPort 2
      - &rightMasterSlave1Port 4
      - &rightMasterSlave2Port 6
      # Digestive system
      - &intakeBumperMotorPort 7
      - &intakeTransitionWheelMotorPort 8
      - &feederMotorPort 9
      - &shooterLeftMotorPort 10
      - &shooterRightMotorPort 11
      - &kickerMotorPort 12
  - SolenoidPorts:
      - &intakeSolenoidForward 2
      - &intakeSolenoidReverse 3
  - DIOPorts:
      - &rightMasterEncoder1Port 0
      - &rightMasterEncoder2Port 1
      - &leftMasterEncoder1Port 2
      - &leftMasterEncoder2Port 3
      - &feederSensor1Port 8
  - JoystickPorts:
      - &mechanismsJoystickPort 0
      - &driveJoystickPort 1
  - DriverButtonNumbers:
      - &driverIntakeOutOn 1 #intakeForward
      - &driverIntakeOff 2 #intakeNeutralDeployed
      - &driverIntakeRev 3 #intakeReverse
      - &driverIntakeInOff 4 #intakeNeutral
      - &fineAdjustLeft 5
      - &fineAdjustRight 6
  - MechsButtonNumbers:
      - &shooterStartClose 1
      - &shooterStartFar 4
      - &shooterStartMid 3
      - &shooterStop 3 # Actually an axis.
      - &shooterStopThrottle 0.8
      - &mechsIntakeInDPad 180
      - &mechsIntakeOutDPad 0
      - &mechsIntakeStop 5
      - &mechsIntakeStart 6
      - &cough 10 # TODO Should coughing be an actual back-and-forth motion?
  - MotorSpeeds:
      - &intakeBumperIntakingVel 1
      - &intakeBumperOutVel -1
      - &intakeTransitionWheelIntakingVel 0.5
      - &feederIndexingVel 0.5
      - &feederShootingVel 0.3 # TODO Was at 0.65, but apparently that's less reliable than 0.35.
      - &feederCoughingVel -0.4
      - &intakeTransitionWheelCoughingVel -0.1
      - &shooterMaxSpeed 90.5 # Unused.
      - &shooterThrottleFar 45.25 # 0.5 * 90.5
      - &shooterThrottleMid 41.63
      - &shooterThrottleClose 41.63
      - &shooterErrorType maxAbsSpeedError
      - &shooterMaxSpeedError 1.25 # In RPS.
      - &shooterMaxSpeedDifferenceType maxAbsSpeedRange
      - &shooterMaxShootingSpeedDifference 0.5 # In RPS.
      - &autoMaxSpeed 2.0 # In meters
      - &autoMaxAccel 1.2 # In meters
      - &kickerThrottle -0.7
  - Other:
      - &feederIndexingTimeoutSecs 60
      - &flywheelSpinUpTimeoutSecs 4
      - &flywheelKP 0.00001
      - &basicAutoDriveBackSpeed -0.3
      - &basicAutoDriveBackTimeSeconds 2
      - &coughDurationSeconds 0.1


#Outright move the joystick classes up here so we don't have to keep figuring out where the first
#usage is whenever we change the commands.
joysticks:
  - org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
      '@id': mechanismsJoystick
      port: *mechanismsJoystickPort
  - org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
      '@id': driveJoystick
      port: *driveJoystickPort

# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false


########################################################################################################################
*PDP:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75


########################################################################################################################
*SUBSYSTEMS:
  - *DRIVE_SUBSYSTEM
  - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyro:
      '@id': drive
      #Wheelbase: 2.14
      leftMaster:
        org.usfirst.frc.team449.robot.generalInterfaces.SmartMotor:
          &Left_Master
          '@id': leftMaster
          type: SPARK
          name: left
          port: *leftMasterPort
          PDP:
            org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
          reverseOutput: true
          enableBrakeMode: true
          #          postEncoderGearing: 0.13333333333
          unitPerRotation: 0.47877872 #meters per rotation
          currentLimit: 50
          enableVoltageComp: true
          encoderCPR: 256
          startingGear: LOW
          perGearSettings:
            - &Low_Gear
              gear: LOW
              postEncoderGearing: 0.0488998
              maxSpeed: 2.3
              kP: 0
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.128
                  kV: 5.23
                  kA: 0.0698
            - &High_Gear
              gear: HIGH
              postEncoderGearing: 0.12936611
              maxSpeed: 5.2
              kP: 0.000001
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.156
                  kV: 2.01
                  kA: 0.154
          slaveSparks:
            - port: *leftMasterSlave1Port
              inverted: false
            - port: *leftMasterSlave2Port
              inverted: false
      rightMaster:
        org.usfirst.frc.team449.robot.generalInterfaces.SmartMotor:
          <<: *Left_Master
          '@id': rightMaster
          type: SPARK
          name: right
          port: *rightMasterPort
          reverseOutput: false
          perGearSettings:
            - <<: *Low_Gear
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.139
                  kV: 5.17
                  kA: 0.0554
            - <<: *High_Gear
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.165
                  kV: 2.01
                  kA: 0.155
          slaveSparks:
            - port: *rightMasterSlave1Port
              PDP: PDP
              inverted: false
            - port: *rightMasterSlave2Port
              PDP: PDP
              inverted: false
      ahrs:
        org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS:
          '@id': navX
          port: kMXP
          invertYaw: true
      trackWidthMeters: 0.61755


########################################################################################################################
*COMMANDS:
  ########################################################################################################################
  *BUTTONS:
    - *DRIVE_COMMANDS
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': fineAdjustRightButtonDrive
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              driveJoystick
          buttonNumber: *fineAdjustRight
      command:
        org.usfirst.frc.team449.robot.drive.unidirectional.commands.AHRS.NavXTurnToAngleRelative:
          &Fine_Adjust_Right_Command
          '@id': fineAdjustRightCommand
          absoluteTolerance: 0
          kP: -0.001
          setpoint: -5.
          drive:
            org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyro:
              drive
          timeout: 1
          inverted: true
      action: WHEN_PRESSED

    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': fineAdjustLeftButtonDrive
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              driveJoystick
          buttonNumber: *fineAdjustLeft
      command:
        org.usfirst.frc.team449.robot.drive.unidirectional.commands.AHRS.NavXTurnToAngleRelative:
          <<: *Fine_Adjust_Right_Command
          '@id': fineAdjustLeftCommand
          kP: 0.001
          setpoint: 5.
          inverted: false
      action: WHEN_PRESSED


  ########################################################################################################################
  *DEFAULT_COMMANDS:
    #***********************************************************************************************************************
    - *DRIVE_DEFAULT_COMMAND
    - subsystem:
        org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyro:
          drive
      command:
        org.usfirst.frc.team449.robot.drive.unidirectional.commands.UnidirectionalNavXDefaultDrive:
          '@id': defaultDriveCommand
          kP: 0.0
          kI: 0.0
          kD: 0.0
          maximumOutput: 1
          absoluteTolerance: 0
          deadband: 2
          maxAngularVelToEnterLoop: 3
          inverted: false
          #          highGearAngularCoefficient: 3
          rampComponent:
            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.RampComponent:
              maxIncreasePerSecond: 3
              maxDecreasePerSecond: 3
          driveStraightLoopEntryTimer:
            '@id': driveStraightLoopEntryTimer
            bufferTimeSeconds: 0.15
          subsystem:
            org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyro:
              drive
          oi:
            org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad:
              '@id': oi
              gamepad:
                org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
                  driveJoystick
              rotThrottle:
                org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                  &rotThrottle
                  '@id': rotThrottle
                  stick: driveJoystick
                  axis: 0
                  smoothingTimeSecs: 0.04
                  deadband: 0.08
                  inverted: false
                  polynomial:
                    org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                      '@id': rotPoly
                      powerToCoefficientMap: !!map
                        1: .5
                  #                        3: .5
                  scale: .7
              fwdThrottle:
                org.usfirst.frc.team449.robot.oi.throttles.ThrottleSum:
                  '@id': fwdThrottle
                  throttles:
                    - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                        <<: *rotThrottle
                        '@id': posThrottle
                        axis: 3
                        inverted: false
                        deadband: 0.05
                        polynomial:
                          org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                            '@id': posPoly
                            powerToCoefficientMap: !!map
                              1: 2
                              2: 1
                    - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                        <<: *rotThrottle
                        '@id': negThrottle
                        axis: 2
                        inverted: true
                        deadband: 0.05
                        polynomial:
                          org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                            '@id': negPoly
                            powerToCoefficientMap: !!map
                              1: 2
                              2: 1
              invertDPad: false
              dPadShift: 0.1
              turnInPlaceRotScale: 1
              rescaleOutputs: true
              scaleRotByFwdPoly:
                org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                  '@id': scaleRotByFwdPoly
                  powerToCoefficientMap: !!map
                    0.5: 0.4
                    0: 0.2
                    #1 : 0.25
                    #2: 0.25
    #          autoshiftComponent:
    #            '@id': autoshiftComponent
    #            upshiftSpeed: 3
    #            downshiftSpeed: 1
    #            upshiftDebouncer:
    #              '@id': upshiftDebouncer
    #              bufferTimeSeconds: 0.06
    #            upshiftFwdThresh: 0.4


  ########################################################################################################################
  *AUTONOMOUS_COMMANDS:
    - *SLALOM_PATH
    - org.usfirst.frc.team449.robot.drive.unidirectional.commands.motionprofiling.RamseteControllerGoToPosition:
        '@id': slalom
        drivetrain:
          org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyro:
            drive
        maxSpeedMeters: 2
        maxAccelMeters: 1.2
        leftPidController:
          org.usfirst.frc.team449.robot.jacksonWrappers.MappedPIDController:
            Kp: 1 # todo
            Ki: 1 # todo
            Kd: 1 # todo
            name: leftPidController
        rightPidController:
          org.usfirst.frc.team449.robot.jacksonWrappers.MappedPIDController:
            Kp: 1 # todo
            Ki: 1 # todo
            Kd: 1 # todo
            name: rightPidController
        endingPose:
          edu.wpi.first.wpilibj.geometry.Pose2d:
            x: 4.121303871674289
            y: -7.246344134510082
            rotation:
              x: -0.7305288926109643
              y: 0.44643432326225696
        translations:
          - x: 4.161888810152676
            y: -12.360046382786832
          - x: 7.327514011466856
            y: -9.965535012562004
          - x: 10.148167235714745
            y: -7.8145332732074975
          - x: 15.525671584101012
            y: -6.962249565161374
          - x: 21.613412355859047
            y: -9.052373896798299
          - x: 24.007923726083874
            y: -11.994781936481349
          - x: 26.787992011853376
            y: -11.913612059524576
          - x: 27.822907943052243
            y: -9.884365135605231
          - x: 26.585067319461444
            y: -7.550731173097983
          - x: 23.80499903369194
            y: -7.5710236423371775
          - x: 21.39019519422792
            y: -11.101913289956837
          - x: 16.215615538233585
            y: -12.847065644527474
          - x: 10.249629581910712
            y: -11.974489467242156
          - x: 6.637570057334278
            y: -9.17412871223346

            ########################################################################################################################
*UPDATER:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
      - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyro: drive
      - org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad: oi
      - org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS: navX