# Automatic code formatting

name: Code Formatting
on: [push, pull_request, workflow_dispatch]
jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "-r"
          commitMessage: "Automated code formatting."
